from pathlib import Path


DATA_FOLDER_PATH = Path("/data")
DATA_RAW_FOLDER_PATH = DATA_FOLDER_PATH.joinpath("01_raw")
DATA_INTERIM_FOLDER_PATH = DATA_FOLDER_PATH.joinpath("02_interim")

DATA_EXTERNAL_FOLDER_PATH = DATA_FOLDER_PATH.joinpath("03_external")
DATA_EXTERNAL_FOLDER_PATH = DATA_FOLDER_PATH.joinpath("04_features")
DATA_EXTERNAL_FOLDER_PATH = DATA_FOLDER_PATH.joinpath("05_model_input")
DATA_EXTERNAL_FOLDER_PATH = DATA_FOLDER_PATH.joinpath("06_models")
DATA_EXTERNAL_FOLDER_PATH = DATA_FOLDER_PATH.joinpath("07_model_output")
DATA_EXTERNAL_FOLDER_PATH = DATA_FOLDER_PATH.joinpath("08_reporing")
